behaviors:
  Runner_Easy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.1
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99    # Aumentado para valorar la meta a largo plazo
        strength: 1.0
      curiosity:       # Añadida curiosidad básica para que encuentre la meta
        strength: 0.1
        network_settings:
          hidden_units: 128
    keep_checkpoints: 5
    checkpoint_interval: 200000
    max_steps: 5000000
    time_horizon: 128  # Aumentado para memorizar trayectorias más largas
    summary_freq: 10000

  Runner_Medium:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.05      # Menos entropía para que sea más preciso en curvas
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256 # Red más grande para niveles más complejos
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.1  # Mayor curiosidad para mapas con más obstáculos
        network_settings:
          hidden_units: 256
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000 # Más pasos sugeridos para dominar el bono de tiempo
    time_horizon: 256
    summary_freq: 20000

  Runner_Hard:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0002 # Aprendizaje más lento para mayor estabilidad
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3    # Tres capas para procesar maniobras evasivas complejas
    reward_signals:
      extrinsic:
        gamma: 0.995   # Máxima importancia a terminar la pista
        strength: 1.0
      curiosity:
        strength: 0.2  # Curiosidad alta para no quedarse atascado en callejones sin salida
        network_settings:
          hidden_units: 256
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 20000000
    time_horizon: 512
    summary_freq: 20000